---
name: Build Documentation w/ MkDocs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}
        #   submodules: recursive

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: Deploy
        run: |
          git pull
          mkdocs gh-deploy
